### ISSUE TITLE
cloud brush

### ISSUE THREAD

**Issue by ekswathi** [Pullusb/GP_refine_strokes#2]
can we do a cloud brush?

**Comment by Pullusb** [comment]
Hello, this question has nothing to do with GP refine stroke.
Please only post issue related to the addon here.
Those questions should be asked on dedicated chats/forums.

To answer anyway:
There is this Brush pack that include a cloud brush: https://cloud.blender.org/p/gallery/5f235cc297f8815e74ffb90b
You can get it directly in Blender by activating the native "Grease pencil tools" addon and then in the brush dropdown menu there will be an option to auto-download the linked pack, as shown on this video at `0:45` : https://vimeo.com/467073917

**Comment by ekswathi** [comment]
Bro,
Please don't misunderstand. when I see the *polygonize* option I think you
are the person ask for it.
The cloud brush is really useful for trees, clouds etc.  I was expecting
something similar to the cad revision cloud something like the link below
https://www.youtube.com/watch?v=0SbF2ZUPw6o
If i am wasting your time sorry for that
thank you

**Comment by Pullusb** [comment]
Hi,
Ok I see now. You're not wasting my time since in the end it is related.
But you definitely got to be more specific in your questions (like providing the example link in the first place).
I assumed you were talking about GP brushes, when it's about a stroke reshaping. Please understand I got to filter when question are out of scope.

Now, about the cloud polygon thing. This addon was never oriented for cad workflow in the first place.
But! I see there could be a use, for comic _thoughts bubble_ and such effects.
So I'll quickly check if it pre-exists in a python math module. Otherwise, I don't think I'll implement it from scratch (really just don't have the time, I wish I had).

What is your use case exactly ?

Also, little tip when you start a conversation with other devs out there:
Introduce (or wrap) your first message with a little greeting, otherwise they'll get the sad feeling of being just a chatGPT ;)

**Comment by ekswathi** [comment]
Bro,
I tried it with texture brushes(I mean greasepencil texture brush).  But it
has some issues.  I just attaached my experiment in youube.
 I didn't mean to use it with cad.  My english is weak. Please take direct
meaning only.
thank you for the kind words and hard work. .
https://www.youtube.com/watch?v=RpBTrEMnxQg
